import { ImInstagram } from "react-icons/im";

const parceiros = [
    {
        nome: "ACI",
        categoria: "mantenedor",
        LogoNormal: require("../../assets/logo/logo-aci-normal.png"),
        LogoWhite: require("../../assets/logo/logo-aci-white.png"),
        tipo: "mantenedor-fundador",
        instagram: "https://www.instagram.com/acipanambirs/",
        linkedin: "https://www.linkedin.com/company/associa%C3%A7%C3%A3o-comercial-e-industrial/",
        website: "https://acipanambi.com/",
        descricao: "",
        logo: "",
        slogan: "",
        telefone: "",
        endereco: "",
        email: "",
        sobre: [],
        items: [],
        segmentos: [],
        produtosDescricao: [],
        produtos: [],
        sede: [],
    },
    {
        nome: "Bruning",
        categoria: "mantenedor",
        LogoNormal: require("../../assets/logo/logo-bruning-normal.png"),
        LogoWhite: require("../../assets/logo/logo-bruning-white.png"),
        tipo: "mantenedor-fundador",
        instagram: "https://www.instagram.com/bruningtecnometal/",
        linkedin: "https://www.linkedin.com/company/bruning-tecnometal/",
        website: "https://bruning.com.br/",
        descricao: "",
        logo: "",
        slogan: "",
        telefone: "",
        endereco: "",
        email: "",
        sobre: [],
        items: [],
        segmentos: [],
        produtosDescricao: [],
        produtos: [],
        sede: [],
     },
    {
        nome: "Cotripal",
        categoria: "mantenedor",
        LogoNormal: require("../../assets/logo/logo-cotripal-normal.png"),
        LogoWhite: require("../../assets/logo/logo-cotripal-white.png"),
        tipo: "mantenedor-fundador",
        instagram: "https://www.instagram.com/cotripal/",
        linkedin: "https://www.linkedin.com/company/cotripal-agropecuária-cooperativa/",
        website: "https://cotripal.com.br/",
        descricao: "",
        logo: "",
        slogan: "",
        telefone: "",
        endereco: "",
        email: "",
        sobre: [],
        items: [],
        segmentos: [],
        produtosDescricao: [],
        produtos: [],
        sede: [],
    },
    {
        nome: "Fockink",
        categoria: "mantenedor",
        LogoNormal: require("../../assets/logo/logo-fockink-normal.png"),
        LogoWhite: require("../../assets/logo/logo-fockink-white.png"),
        tipo: "mantenedor-fundador",
        instagram: "https://www.instagram.com/fockink_ind/",
        linkedin: "https://www.linkedin.com/company/grupo-fockink/",
        website: "https://fockink.ind.br/",
        descricao: "",
        logo: "",
        slogan: "",
        telefone: "",
        endereco: "",
        email: "",
        sobre: [
            "A trajetória da Fockink iniciou no ano de 1947 com uma pequena oficina de rebobinagem e conserto de motores elétricos, sempre comprometida com a excelência dos serviços prestados, preserva ao longo de seus mais de 77 anos a mesma ideologia de seu fundador, Alfredo Arnaldo Fockink, de que “a melhor propaganda é o serviço”.",
            "Uma empresa familiar e 100% brasileira, sólida e bem estruturada que se tornou referência nos segmentos em que atua.",
            "Gerando soluções e integrando tecnologias a Fockink desenvolve Sistemas de Irrigação, Sistemas de Geração Fotovoltaica, Sistemas de Termometria e Aeração, Biogás, Subestações, Painéis Elétricos e Automação, Instalações Eletromecânicas e Painéis e Caixas Metálicas Vazias.",
            "Nossa missão é entregar aos nossos clientes soluções de forma sustentável e íntegra, respeitando o meio ambiente, a qualidade dos nossos produtos e serviços e não comprometendo a segurança das pessoas, nossa visão é ser referência nacional, sempre com foco em inovação, gerando soluções e integrando tecnologias e nossos valores são Segurança, Qualidade, Respeito, Integridade e Profissionalismo."
        ],
        items: [],
        segmentos: [{texto: "Agro e Industrias."}],
        produtosDescricao: [],
        produtos: [],
        sede: [],
    },
    {
        nome: "KeplerWeber",
        categoria: "mantenedor",
        LogoNormal: require("../../assets/logo/logo-keplerweber-normal.png"),
        LogoWhite: require("../../assets/logo/logo-keplerweber-white.png"),
        tipo: "mantenedor-fundador",
        instagram: "https://www.instagram.com/keplerweber/",
        linkedin: "https://www.linkedin.com/company/keplerweber/",
        website: "https://kepler.com.br/",
        descricao: "",
        logo: "",
        slogan: "",
        telefone: "",
        endereco: "",
        email: "",
        sobre: [],
        items: [],
        segmentos: [],
        produtosDescricao: [],
        produtos: [],
        sede: [],
    },
    {
        nome: "Pref. Municipal de Panambi",
        categoria: "mantenedor",
        LogoNormal: require("../../assets/logo/logo-prefeitura-normal.png"),
        LogoWhite: require("../../assets/logo/logo-prefeitura-normal.png"),
        tipo: "mantenedor-fundador",
        instagram: "https://www.instagram.com/prefeiturapanambi/",
        linkedin: "https://www.linkedin.com/company/prefeitura-municipal-de-panambi/about/",
        website: "https://panambi.atende.net/",
        descricao: "",
        logo: "",
        slogan: "",
        telefone: "",
        endereco: "",
        email: "",
        sobre: [],
        items: [],
        segmentos: [],
        produtosDescricao: [],
        produtos: [],
        sede: [],
    },
    {
        nome: "SAUR",
        categoria: "mantenedor",
        slogan: "a líder em movimento ",
        LogoNormal: require("../../assets/logo/logo-saur-normal.png"),
        LogoWhite: require("../../assets/logo/logo-saur-white.png"),
        logo: require("../../assets/logo/logo-saur-650x365.png"),
        tipo: "associado-fundador",
        telefone: "3376-9300",
        endereco: "Av. Pres. Kennedy, 4025 - Arco-Íris, Panambi - RS, 98280-000",
        email: "site@saur.com.br",
        instagram: "https://www.instagram.com/saurequipamentos/",
        linkedin: "https://www.linkedin.com/company/saur-equipamentos-s.a./",
        website: "https://saur.com.br/",
        sobre: [
            "A história da SAUR começou em 1926, quando o imigrante alemão Richard Saur, fundou uma pequena oficina de reparos, na cidade de Panambi-RS. Com sua coragem e determinação na década seguinte passou a fabricar vários produtos. E, alguns anos depois, quando o filho Ernesto Otto Saur assumiu a administração da empresa, novos projetos foram desenvolvidos, vislumbrando as oportunidades do mercado no setor de movimentação de cargas. ",
            "Hoje, os equipamentos SAUR estão presentes em mais de 40 países localizados na América, Europa, Ásia e África, conquistando a liderança no fornecimento de Plataformas de Descarga para Granéis na América Latina e sendo referência em equipamentos para empilhadeiras na América do Sul. ",
            "Desde o início de suas atividades sempre primou pela excelência de seus produtos e serviços, contribuindo para o desenvolvimento da economia e da sociedade onde atua, para preservar os recursos naturais e apoiar diversas ações voltadas à educação, à cultura e ao bem-estar de seus colaboradores e da comunidade, indo ao encontro da ASG – Ambiental, Social e Governança. ",
        ],
        items: [
            { titulo: "Propósito", texto: "Movimentar riquezas e gerar emprego e renda de forma responsável." },
            { titulo: "Visão", texto: "Ser líder na América Latina e referência global em soluções logísticas inovadoras." },
            { titulo: "Missão", texto: "Desenvolver, produzir e comercializar soluções logísticas para movimentação de cargas e materiais, garantindo a satisfação dos clientes, acionistas e colaboradores, com desenvolvimento sustentável. " },
        ],
        segmentos: [
            { titulo: "Setor Agrícola:", texto: " Seus principais equipamentos são Plataformas para Descarga de Granéis, Cabines de Captação de Pó, Coletores de Amostras de Cereais e Basculadores de Containers, que proporcionam mais eficiência e agilidade no recebimento dos grãos." },
            { titulo: "Setor Industrial:", texto: "Comercializa equipamentos acoplados em empilhadeiras, como Garras para Fardos e Caixas, Garra para Caixas, Garras para Bobinas, Garras para Tambores e Bombonas, Garras para Pneus e Rodas, Inversores e Empurradores de Cargas, Posicionador de Garfos. Também disponibiliza Rampas Niveladoras de Docas e Rampas Niveladoras, Plataformas Elevadoras, além de outros equipamentos que tornam a movimentação de cargas com alta performance, ergonomia e qualidade." },
            { titulo: "Setor Florestal:", texto: "Gruas Florestais acopladas em Trator, Gruas Florestais Estacionárias, Autocarregáveis e Carretas, Gruas Sucateiras e Garras Florestais, conferindo agilidade na movimentação e transportes de cargas." },
            { titulo: "Equipamentos Especiais:", texto: "Desenvolvidos de acordo com as necessidades específicas de cada cliente, trazendo eficiência nas operações.  " }
        ],
        produtosDescricao: [

        ],
        produtos: [
            { imagem: require("../../assets/produtos/SAUR-4.png"), titulo: "Linha Agrícola-Plataforma de Descarga para Granéis" },
            { imagem: require("../../assets/produtos/SAUR-3.png"), titulo: "Linha Florestal-Grua Florestal" },
            { imagem: require("../../assets/produtos/SAUR-2.png"), titulo: "Linha Industrial-Garra para Bobinas" },
            { imagem: require("../../assets/produtos/SAUR-1.png"), titulo: "Equipamentos Especiais-Spreeder" },

        ],
        sede: [
            { imagem: require("../../assets/sedes/SAUR-SEDE.png"), alt: "Sede da Saur" },
        ]
    },
    {
        nome: "TROMINK",
        categoria: "mantenedor",
        slogan: "soluções para armazenagem e beneficiamento de grãos",
        LogoNormal: require("../../assets/logo/logo-tromink-normal.png"),
        LogoWhite: require("../../assets/logo/logo-tromink-white.png"),
        logo: require("../../assets/logo/logo-tromink-650x365.png"),
        tipo: "mantenedor-fundador",
        telefone: "(55) 3030-3000",
        endereco: "Avenida dos Imigrantes, 1075 - Distrito Industrial | Panambi/RS",
        email: "vendas@tromink.com.br",
        instagram: "https://www.instagram.com/trominkindustrial/",
        linkedin: "https://www.linkedin.com/company/tromink/",
        website: "https://tromink.com.br/",
        sobre: [
            "A Tromink iniciou suas atividades em 14 de outubro de 1992, revendendo insumos para empresas locais. Após o início da empresa, seu fundador, percebeu na terceirização de serviços um nicho de mercado, e passou a ver na indústria, o propósito de seu negócio.",
            "Desde então, sempre com o olhar atento ao mercado, a empresa passou a desenvolver seus próprios produtos voltados para o segmento agrícola, fabricando peças para unidades armazenadoras de grãos. Com o time de profissionais comprometidos e engajados, com o passar do tempo, a empresa tornou-se referência em soluções para o agronegócio.",
            "Em 2009, a empresa passou a conquistar novos mercados, passando também a atuar no segmento de implementos agrícolas e atualmente, é fornecedora para as maiores montadoras agrícolas do país, com peças para colheitadeiras, plantadeiras e tratores.",
            "Já são 30 anos de muitos desafios, oportunidades e conquistas, e hoje a empresa atua nos segmentos de armazenagem, montadoras agrícolas e também na construção civil.Atualmente, a Tromink conta com 700 colaboradores, com sede em Panambi / RS e uma estrutura na cidade de Rio Verde / GO.Com esse time de pessoas, a empresa ultrapassa fronteiras, atendendo toda a América Latina, Europa e EUA."
        ],
        items: [
        ],
        segmentos: [
            { titulo: "", texto: " Armazenagem, montadoras agrícolas e também na construção civil." }, // Placeholder até ter dados específicos
        ],
        produtosDescricao: [
            {
                titulo: "Silos:",
                descricao: "A linha de silos para Armazenagem de Grãos STOK proporciona eficiência e segurança na preservação da safra. Projetados para diferentes capacidades de armazenagem, possuem estrutura resistente às intempéries climáticas e telhado desenvolvido para suportar grandes cargas. O sistema de aeração garante a qualidade e integridade dos grãos armazenados."
            },
            {
                titulo: "Máquinas de Limpeza MALT:",
                descricao: "As Máquinas de Limpeza MALT da Tromink são projetadas para pré-limpeza e limpeza de grãos com segurança. Possuem corpo blindado para reduzir a emissão de pó e ruído, base metálica opcional para menor custo civil e sistema de dupla aspiração. Com maior área de peneiras e acesso ergonômico, oferecem eficiência e agilidade no processo.",
                beneficios: [
                    "Corpo Blindado: maior segurança, menor emissão de pó, baixo ruído",
                    "Base metálica: base metálica opcional, menor custo Civil",
                    "Dupla Aspiração: câmara de pré-aspiração (antes da limpeza do grão) e pós-aspiração (depois da limpeza do grão)",
                    "Quadro de comando: quadro de comando opcional, ajuste de aspiração de impurezas finas",
                    "Alta eficiência: maior área de peneiras, quadros individuais, agilidade no setup",
                    "Ergonomia: acesso amplo e normatizado"
                ]
            },
            {
                titulo: "Secadores:",
                descricao: "Os secadores de colunas Tromink linha SCOT foram projetados para eficiência e segurança no processo de secagem. Com capacidades contínuas de 20 Ton/h a 300 Ton/h, são modulares e adequados para diferentes tipos de grãos, sejam para fins comerciais ou produção de sementes.",
            },
            {
                titulo: "Elevadores:",
                descricao: "Os elevadores ECTR da Tromink são projetados para transporte vertical de grãos, atendendo às principais normas de segurança agrícola."
            }
        ],
        produtos: [
            { imagem: require("../../assets/produtos/TROMINK-1.png"), titulo: "SILO" },
            { imagem: require("../../assets/produtos/TROMINK-5.png"), titulo: "SILO" },
            { imagem: require("../../assets/produtos/TROMINK-6.png"), titulo: "SILO" },
            { imagem: require("../../assets/produtos/TROMINK-2.png"), titulo: "ELEVADOR" },
            { imagem: require("../../assets/produtos/TROMINK-3.png"), titulo: "MALT" },
            { imagem: require("../../assets/produtos/TROMINK-4.png"), titulo: "SECADOR" },
        ],
        sede: [
            { imagem: require("../../assets/sedes/TROMINK-SEDE.png"), alt: "Sede da Tromink" } // Sem imagem fornecida
        ]
    },

    {
        nome: "3tentos",
        categoria: "mantenedor",
        LogoNormal: require("../../assets/logo/logo-3tentos-normal.png"),
        LogoWhite: require("../../assets/logo/logo-3tentos-white.png"),
        tipo: "mantenedor",
        instagram: "https://www.instagram.com/3tentos/",
        linkedin: "https://www.linkedin.com/company/3tentosagro/",
        website: "https://3tentos.com.br/",
        descricao: "",
        logo: "",
        slogan: "",
        telefone: "",
        endereco: "",
        email: "",
        sobre: [],
        items: [],
        segmentos: [],
        produtosDescricao: [],
        produtos: [],
        sede: [],
    },

    {
        nome: "Coprel",
        categoria: "associado",
        tipo: "associado",
        LogoNormal: require("../../assets/logo/logo-coprel-normal.png"),
        LogoWhite: require("../../assets/logo/logo-coprel-white.png"),
        instagram: "https://www.instagram.com/coprelenergia/",
        linkedin: "https://www.linkedin.com/company/coprel",
        website: "https://www.coprel.com.br/",
        descricao: "",
        logo: "",
        slogan: "",
        telefone: "",
        endereco: "",
        email: "",
        sobre: [],
        items: [],
        segmentos: [],
        produtosDescricao: [],
        produtos: [],
        sede: [],

    },
    {
        nome: "DomTI",
        categoria: "associado",
        tipo: "associado",
        LogoNormal: require("../../assets/logo/logo-domti-normal.png"),
        LogoWhite: require("../../assets/logo/logo-domti-white.png"),
        instagram: "https://www.instagram.com/domtisolucoes/",
        linkedin: "https://www.linkedin.com/company/domti-solu%C3%A7%C3%B5es/",
        website: "https://domti.tech/",
        descricao: "",
        logo: "",
        slogan: "",
        telefone: "",
        endereco: "",
        email: "",
        sobre: [],
        items: [],
        segmentos: [],
        produtosDescricao: [],
        produtos: [],
        sede: [],
    },
    {
        nome: "Easypro Tech",
        categoria: "associado",
        tipo: "associado",
        LogoNormal: require("../../assets/logo/logo-easypro-normal.png"),
        LogoWhite: require("../../assets/logo/logo-easypro-white.png"),
        instagram: "https://www.instagram.com/easypro_tecnologia/",
        linkedin: "https://www.linkedin.com/company/easyprotecnologia/",
        website: "https://www.easypro.com.br/",
        descricao: "",
        logo: "",
        slogan: "",
        telefone: "",
        endereco: "",
        email: "",
        sobre: [],
        items: [],
        segmentos: [],
        produtosDescricao: [],
        produtos: [],
        sede: [],
    },
    {
        nome: "Madereira 2 Irmãos",
        categoria: "associado",
        tipo: "associado",
        LogoNormal: require("../../assets/logo/logo-madereira-normal.png"),
        LogoWhite: require("../../assets/logo/logo-madereira-white.png"),
        instagram: "https://www.instagram.com/arcanomadeiras/",
        linkedin: "https://www.linkedin.com/company/arcanomadeiras/",
        website: "https://www.madeireira2irmaos.com/",
        descricao: "",
        logo: "",
        slogan: "",
        telefone: "",
        endereco: "",
        email: "",
        sobre: [],
        items: [],
        segmentos: [],
        produtosDescricao: [],
        produtos: [],
        sede: [],
    },
    {
        nome: "NBRtec",
        categoria: "associado",
        tipo: "associado",
        LogoNormal: require("../../assets/logo/logo-nbrtec-normal.png"),
        LogoWhite: require("../../assets/logo/logo-nbrtec-white.png"),
        instagram: "https://www.instagram.com/nbrtec/",
        linkedin: "https://www.linkedin.com/company/nbrtec/",
        website: "https://www.nbrtec.com.br/",
        descricao: "",
        logo: "",
        slogan: "",
        telefone: "",
        endereco: "",
        email: "",
        sobre: [],
        items: [],
        segmentos: [],
        produtosDescricao: [],
        produtos: [],
        sede: [],
    },
    {
        nome: "Pontes Máquinas",
        categoria: "associado",
        tipo: "associado",
        LogoNormal: require("../../assets/logo/logo-pontes-normal.png"),
        LogoWhite: require("../../assets/logo/logo-pontes-white.png")
    },
    {
        nome: "Sirros IoT",
        categoria: "associado",
        tipo: "associado",
        LogoNormal: require("../../assets/logo/logo-sirros-normal.png"),
        LogoWhite: require("../../assets/logo/logo-sirros-white.png"),
        instagram: "https://www.instagram.com/sirrosiot/",
        linkedin: "https://www.linkedin.com/company/sirros-iot",
        website: "https://sirros.io/",
        descricao: "",
        logo: "",
        slogan: "",
        telefone: "",
        endereco: "",
        email: "",
        sobre: [],
        items: [],
        segmentos: [],
        produtosDescricao: [],
        produtos: [],
        sede: [],
    },
    {
        nome: "SKA",
        categoria: "associado",
        tipo: "associado",
        LogoNormal: require("../../assets/logo/logo-ska-normal.png"),
        LogoWhite: require("../../assets/logo/logo-ska-white.png"),
        instagram: "https://www.instagram.com/ska_oficial/",
        linkedin: "https://www.linkedin.com/company/ska-automacao-engenharias",
        website: "https://ska.com.br/",
        descricao: "",
        logo: "",
        slogan: "",
        telefone: "",
        endereco: "",
        email: "",
        sobre: [],
        items: [],
        segmentos: [],
        produtosDescricao: [],
        produtos: [],
        sede: [],

    },
    {
        nome: "Yawei Brasil",
        categoria: "associado",
        tipo: "associado",
        LogoNormal: require("../../assets/logo/logo-yawei-normal.png"),
        LogoWhite: require("../../assets/logo/logo-yawei-white.png"),
        instagram: "https://www.instagram.com/yaweibrasil/",
        linkedin: "https://www.linkedin.com/company/yawei-brasil",
        website: "https://yawei.com.br/",
        logo: "",
        slogan: "",
        telefone: "",
        endereco: "",
        email: "",
        sobre: [],
        items: [],
        segmentos: [],
        produtosDescricao: [],
        produtos: [],
        sede: [],
    },
]


export default parceiros;